name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and send email
        run: |
          set -x 
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv install requests
          pipenv run python src/send_email.py --owner sachinsts --authtoken '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'
