name: GitHub Actions Demo
on:
   workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies and send email
        run: |
          set -x 
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv install requests
          pipenv run python src/scan_repo.py --owner "sachinsts" --authtoken ${{ secrets.PAT }}
